# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"


# Allow users to fix the underlying OS via singularity.
container: "docker://continuumio/miniconda3"


##### check snakemake min version #####

from snakemake.utils import min_version

min_version("7.15.2")


include: "rules/common.smk"
include: "rules/centering.smk"
include: "rules/tiling.smk"
include: "rules/oligo_design.smk"


rule all:
    input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.
        expand("results/final_design/{sample}/design.fa", sample=datasets.index),
        expand(
            "results/oligo_design/{sample}/filtered.variants.vcf.gz",
            sample=getVariantDatasets(),
        ),
        expand(
            "results/oligo_design/{sample}/filtered.regions.bed.gz",
            sample=getRegionDatasets(),
        ),
