wrapper_directory: /data/gpfs-1/users/schubacm_c/work/projects/snakemake_wrappers
reference:
  genome: /fast/projects/cubit/current/static_data/reference/GRCh38/hs38/hs38.fa.genome
  fasta: /fast/projects/cubit/current/static_data/reference/GRCh38/hs38/hs38.fa
samples: "config/samples.tsv"

oligo_length: 270

tiling:
  remove_edge_variants: true
  min_overlap: 50
  strategies:
    two_tiles:
      min: 350
      include_variant_edge: true
  variant_edge_exclusion: 25
